# Components.py
COMPONENTS = {
    "Слова силы": {
        "Аура": "Auram",
        "Вода": "Aqua",
        "Воздух": "Aer",
        "Голод": "Fames",
        "Гроза": "Tempestas",
        "Движение": "Motus",
        "Девушка": "Virgo",
        "Дерево": "Arbor",
        "Добыча": "Perfodio",
        "Дух": "Spiritus",
        "Жатва": "Meto",
        "Жизнь": "Victus",
        "Защита": "Tutamen",
        "Зверь": "Bestia",
        "Земля": "Terra",
        "Зло": "Malum",
        "Звук": "Sonus",
        "Исцеление": "Sano",
        "Инструмент": "Instrumentum",
        "Кровь": "Sanguinis",
        "Ловушка": "Vinculum",
        "Луна": "Luna",
        "Лёд": "Gelum",
        "Маг. урон": "Corpiris Praecantatio",
        "Магия": "Praecantatio",
        "Материя": "Pannus",
        "Металл": "Metallum",
        "Механизм": "Machina",
        "Молния": "Fulmen",
        "Молоко": "Lac",
        "Мужчина": "Guido",
        "Нежить": "Exanimis",
        "Неизвестное": "Aliens",
        "Огонь": "Ignis",
        "Осязание": "Sensus",
        "Оружие": "Telum",
        "Переплавка": "Liquescens",
        "Плоть": "Corpus",
        "Полёт": "Volatus",
        "Порча": "Vitium",
        "Порядок": "Ordo",
        "Пустота": "Vacous",
        "Путешествие": "Iter",
        "Разрушение": "Perditio",
        "Разум": "Cognitio",
        "Рост": "Permutatio",
        "Свет": "Lux",
        "Слепота": "un'lux",
        "Смерть": "Mortuus",
        "Создать": "Fabrico",
        "Солнце": "Sol",
        "Стекло": "Vitreus",
        "Тепло": "Calidium",
        "Тишина": "Silentium",
        "Толчок": "Ventilabis",
        "Тьма": "Tenebrae",
        "Удушие": "Suffocatio",
        "Урожай": "Messis",
        "Физ. урон": "Corporis",
        "Флора": "Herba",
        "Человек": "Humanus",
        "Холод": "Frigore",
        "Энергия": "Potentia",
        "Яд": "Venenum",
        "Нести": "Fero",
        "Мир": "Mundo",
        "Пространство": "Spatium",
        "Страдание": "Malum",
        "Песок": "Arena",
        "Добродетель": "Virtus",
        "Грех": "Peccatum",
    },
    "Слова цели": {
        "Я": "Ego",
        "Цель": "Eam",
        "Мы": "Nos",
        "На себя": "Ad Te Ipsum",
        "Стена": "Murum",
        "Точка": "Point",
        "Внутри": "Intra",
    },
    "Слова формы": {
        "Взгляд": "Intentio",
        "Касание": "Tactus",
        "Луч": "Trabem",
        "Снаряд": "Missile",
        "Волна": "Fluctus",
        "Призыв": "Summon",
        "Зона": "Zonam",
    },
    "Слова дополнения": {
        "Днём сильнее": "La Forza della Sol",
        "Ночью сильнее": "La Forza della Eclipse",
        "Ослабление": "La Debilitare",
        "Отскок": "La Repente",
        "Пронизывание": "La Pungentes",
        "Урон": "La Damnum",
        "Усиление": "La Fortitudo",
        "Мощность": "La Fortitudo",
        "Ускорение": "La Celeritas",
        "Физика": "La Gravitas",
        "Эффект по площади": "La Area",
    },
    "Слова греха": {
        "Лень": "Desidia",
        "Обжорство": "Gula",
        "Зависть": "Invidia",
        "Гнев": "Ira",
        "Похоть": "Luxuria",
        "Гордость": "Superbia",
        "Жадность": "Lucrum",
        "Тщеславие": "Vanitas",
        "Ад": "Infernus",
    },
    "Слова благодетели": {
        "Целомудрие": "Castitas",
        "Умеренность": "Temperantia",
        "Любовь": "Caritas",
        "Усердие": "Industria",
        "Терпение": "Patientia",
        "Доброта": "Humanitas",
        "Смирение": "Humilitas",
    },
    "Слова времени": {
        "Время": "Tempore",
        "Назад": "Restursum",
        "Вперёд": "Protinus",
        "Петля": "Loop",
        "Секунда": "Secundo",
        "Минута": "Minute",
        "Час": "Hora",
        "День": "Dies",
        "Год": "Annus",
        "Век": "Saeculum",
        "Начало": "Principium",
        "Конец": "Finis Tempore",
        "Вечность": "Aeternitas",
    },
    "Условия и прочее": {
        "от": "a",
        "и": "et",
        "но": "sed",
        "из": "ab",
        "из-за": "quia",
        "не": "not",
        "анти": "un'",
        "повтор": "re'",
        "полу": "dimi'",
        "действие": "tu",
        "сущность": "es",
        "если": "si",
        "то": "modo",
        "иначе": "aliver",
        ">": "magis",
        "<": "minus",
        "==": "aequalis",
        ">=": "magis'ae",
        "<=": "minus'ae",
        "содержит": "continet",
        "или": "aut",
    },
    "Математика": {
        "+": "praeterea",
        "-": "sub",
        "*": "mult",
        "/": "div",
        "Минус": "negatio'",
        "0": "Nulla",
        "1": "Uno",
        "2": "Dos",
        "3": "Tres",
        "4": "Quadro",
        "5": "Quinque",
        "6": "Six",
        "7": "Septem",
        "8": "Octo",
        "9": "Novem",
    },
    "Существа": {
        "Кот": "es Bestia Desidia",
        "Волк": "es Bestia",
        "Конь": "es Bestia Motus",
        "Корова": "es Bestia Lac",
        "Птица": "es Bestia Volatus",
        "Курица": "es Bestia un'Volatus",
        "Ящер": "es Bestia Terra",
        "Змея": "es Bestia Terra Invidia",
        "Рыба": "es Bestia Aqua",
        "Лиса": "es Bestia Sonus",
        "Кит": "es Bestia Aqua et un'Aqua",
        "Паук": "es Bestia Venenum",
        "Мышь": "es Bestia La Debilitare",
        "Летучая мышь": "es Bestia La Debilitare Sanguinis Volatus",
    },
    "Маг. Существа": {
        "Дементор": "es Spiritus Frigore Mortuus",
        "Вампир": "es Humanus Exanimis Sanguinis",
        "Оборотень": "es Humanus Bestia Luna",
        "Фестрал": "es Bestia Motus quia Mortuus",
        "Дракон": "es Bestia Terra Volatus Lucrum",
        "Василиск": "es Bestia Terra Invidia Intentio Mortuus",
        "Куролиск": "es Bestia Terra un'Volatus Invidia Intentio Mortuus",
        "Гиппогриф": "es Bestia Desidia dimi'Bestia Volatus et Superbia",
        "Гиппогамп": "es Bestia Motus dimi'Bestia Aqua",
        "Единорог": "es Bestia Motus Praecantatio",
        "Тёмный единорог": "es Bestia Motus Praecantatio Malum",
        "Пегас": "es Bestia Motus Volatus",
        "Аликорн": "es Bestia Motus Volatus Praecantatio",
        "Морской змей": "es Bestia un'Terra Invidia Aqua",
        "Амфитера": "es Bestia un'Terra Invidia Aer Volatus",
    },
    "Миры": {
        "Вневременная Пустошь": "Mundo Tempore aequalis Spatium",
        "Первый Круг": "Mundo Vacous not Lux",
        "Второй Круг": "Mundo Luxuria Loop Tempestas",
        "Третий Круг": "Mundo Gula Gelum",
        "Четвёртый Круг": "Mundo Lucrum Vanitas Loop Motus",
        "Пятый Круг": "Mundo Ira et Desidia Suffocatio",
        "Шестой Круг": "Mundo Malum Ignis Vinculum",
        "Седьмой Круг": "Mundo Luxuria Malum Sanguinis Calidium",
        "Восьмой Круг": "Mundo Invidia Venenum es Bestia Terra Invidia Tenebrae",
        "Девятый Круг": "Mundo Infernus Gelum Aeternitas",
        "Мир Людей": "Mundo Victus Humanus Tempore",
    },
    "Выше людей": {
        "Божество": "es Deus",
        "Серафим": "es Angelo Uno",
        "Херувим": "es Angelo Dos",
        "Престол": "es Angelo Tres",
        "Господство": "es Angelo Quadro",
        "Сила": "es Angelo Quinque",
        "Власть": "es Angelo Six",
        "Начало": "es Angelo Septem",
        "Архангел": "es Angelo Octo",
        "Ангел": "es Angelo",
        "Дьявол": "es Diablo",
        "Люцифер": "Lucifer es un'Angelo Superbia",
        "Белилал": "Belial es Daemon Malus",
        "Бельфегор": "Belphegor es Daemon Desidia",
        "Левиафан": "Leviathan es Daemon Invidia",
        "Мамон": "Mammon es Daemon Lucrum",
        "Сатана": "satanas es Daemon Ira",
        "Вельзевул": "Beelzebub es Daemon Gula",
        "Пифон": "Python es Daemon Protinus",
        "Баал": "Baal",
        "Бафомет": "Bapthometus",
        "Азазель": "Azazel",
        "Лилит": "Lamia es Malus Virgo",
        "Асмодей": "Asmodeus es Daemon Luxuria",
        "Мерезин": "Meresin es Daemon Tempestas",
        "Астарот": "Astharoth es Daemon Vanitas",
        "Абаддон": "Abaddon es Daemon Telum",
        "Демон": "es Daemon",
        "Всадник Смерть": "es Mortuus",
        "Всадник Голод": "es Fames",
        "Всадник Война": "es Telum",
        "Всадник Чума": "es Venenum",
        "Смотрящий": "es Tempore",
    },
    "Паттерны": {
        "Холодостойкость": "Tutamen a Frigore",
        "Жаростойкость": "Tutamen a un'Frigore",
        "Фаерболл": "Missile Ignis",
        "Морозный луч 5": "Trabem Frigore power Quinque",
        "Радиация": "Aer Venenum Potentia",
        "Кража магии": "tu Meto Praecantatio Fero",
        "C4": "Fluctus Potentia et Calidium La Area 4 et La Fortitudo 4",
        "Динамит": "Fluctus Potentia et Calidium La Area 5 et La Fortitudo 5",
        "Нитроглицерин": "Fluctus Potentia et Calidium La Area 5 et La Fortitudo 6",
        "Малыш": "Fluctus Potentia et Calidium et Aer Venenum Potentia La Area 60 et La Fortitudo 80",
        "Толстяк": "Fluctus Potentia et Calidium et Aer Venenum Potentia La Area 100 et La Fortitudo 100",
        "Царь-бомба": "Fluctus Potentia et Calidium et Aer Venenum Potentia La Area 1000 et La Fortitudo 1000",
        "Водородная бомба": "Fluctus Potentia La Area 200 et La Fortitudo 200",
        "Телепорт": "Praecantatio Iter Ego Point",
        "Вечный шар света": "Point Lux Aeternitas",
    },
}
