# Components.py

COMPONENTS = {
    "Слова силы": {
        "Аура": "Praecantatio",
        "Вода": "Aqua",
        "Воздух": "Aer",
        "Голод": "Fames",
        "Гроза": "Tempestas",
        "Движение": "Motus",
        "Девушка": "Virgo",
        "Дерево": "Arbor",
        "Добыча": "Perfodio",
        "Дух": "Spiritus",
        "Жатва": "Meto",
        "Жизнь": "Victus",
        "Защита": "Tutamen",
        "Земля": "Terra",
        "Зло": "Malum",
        "Исцеление": "Sano",
        "Кровь": "Sanguinis",
        "Ловушка": "Vinculum",
        "Луна": "Luna",
        "Лёд": "Gelum",
        "Маг. урон": "Corpiris Praecantatio",
        "Магия": "Auram",
        "Материя": "Pannus",
        "Металл": "Metallum",
        "Механизм": "Machina",
        "Молния": "Fulmen",
        "Молоко": "Lac",
        "Мужчина": "Guido",
        "Нежить": "Exanimis",
        "Неизвестное": "Aliens",
        "Огонь": "Ignis",
        "Осязание": "Sensus",
        "Переплавка": "Liquescens",
        "Плоть": "Corpus",
        "Полёт": "Volatus",
        "Порча": "Vitium",
        "Порядок": "Ordo",
        "Пустота": "Vacous",
        "Путешествие": "Iter",
        "Разрушение": "Perditio",
        "Разум": "Cognitio",
        "Рост": "Permutatio",
        "Свет": "Lux",
        "Слепота": "Un'lux",
        "Смерть": "Mortuus",
        "Создать": "Fabrico",
        "Солнце": "Sol",
        "Стекло": "Vitreus",
        "Тепло": "Calidium",
        "Тишина": "Silentium",
        "Толчок": "Ventilabis",
        "Тьма": "Tenebrae",
        "Удушие": "Suffocatio",
        "Урожай": "Messis",
        "Физ. урон": "Corporis",
        "Флора": "Herba",
        "Холод": "Frigore",
        "Энергия": "Potentia",
        "Яд": "Venenum"
    },
    "Слова цели": {
        "Я": "Ego", 
        "Цель": "Eam", 
        "Мы": "Nos", 
        "На себя": "Ad Te Ipsum",
        "Стена": "Murum", 
        "Человек": "Humanus", 
        "Инструмент": "Instrumentum",
        "Зверь": "Bestia"
    },
    "Слова формы": {
        "Намерение": "Intentio", 
        "Касание": "Tactus", 
        "Луч": "Trabem",
        "Снаряд": "Missile", 
        "Волна": "Fluctus", 
        "Зона": "Zonam"
    },
    "Слова дополнения": {
        "Днём сильнее": "La Forza della Sol",
        "Ночью сильнее": "La Forza della Eclipse",
        "Ослабление": "La Debilitare",
        "Отскок": "La Repente",
        "Пронизывание": "La Pungentes",
        "Урон": "La Damnum",
        "Усиление": "La Fortitudo",
        "Ускорение": "La Celeritas",
        "Физика": "La Gravitas",
        "Эффект по площади": "La Area"
    },
    "Слова греха": {
        "Лень": "Desidia", 
        "Обжорство": "Gula", 
        "Зависть": "Invidia",
        "Гнев": "Ira", 
        "Похоть": "Luxuria", 
        "Гордость": "Superbia",
        "Жадность": "Lucrum", 
        "Тщеславие": "Vanitas", 
        "Ад": "Infernus"
    },
    "Слова благодетели": {
        "Целомудрие": "Castitas", 
        "Умеренность": "Temperantia",
        "Любовь": "Caritas", 
        "Усердие": "Industria",
        "Терпение": "Patientia", 
        "Доброта": "Humanitas",
        "Смирение": "Humilitas"
    },
    "Слова времени": {
        "Время": "Tempore", 
        "Назад": "Restursum", 
        "Вперёд": "Protinus",
        "Петля": "Loop", 
        "Секунда": "Secundo", 
        "Минута": "Minute",
        "Час": "Hora", 
        "День": "Dies", 
        "Год": "Annus", 
        "Век": "Saeculum",
        "Начало": "Principium", 
        "Конец": "Finis Tempore"
    },
    "Условия и прочее": {
        "от": "a", 
        "и": "et", 
        "но": "sed", 
        "из": "ab", 
        "из-за": "quia",
        "не": "not", 
        "анти": "un'", 
        "повтор": "re'", 
        "полу": "dimi'", 
        "действие": "tu",
        "существо": "es", 
        "если": "si", 
        "то": "modo", 
        "иначе": "aliver"
    },
    "Существа":
    {
        "Кот": "es Bestia Desidia",
        "Волк": "es Bestia",
        "Конь": "es Bestia Motus",
        "Корова": "es Bestia Lac Virgo",
        "Птица": "es Bestia Volatus",
        "Ящер": "es Bestia Terra",
        "Змея": "es Bestia Terra Invidia",
        "Рыба": "es Bestia Aqua"
    },
    "Маг. Существа":
    {
        "Дементор": "es Spiritus Frigore Mortuus",
        "Вампир": "es Humanus Exanimis Sanguinis",
        "Оборотень": "es Humanus Bestia Luna",
        "Фестрал": "es Bestia Motus quia Mortuus",
        "Дракон": "es Bestia Terra Volatus Lucrum",
        "Василиск": "es Bestia Terra Invidia Intentio Mortuus",
        "Куролиск": "es Bestia Terra un'Volatus Invidia Intentio Mortuus",
        "Гиппогриф": "es Bestia Desidia dimi'Bestia Volatus et Superbia",
        "Гиппогамп": "es Bestia Motus dimi'Bestia Aqua"
    },
    "Паттерны": {
        "Холодостойкость": "Ad Te Ipsum Tutamen a Frigore",
        "Жаростойкость": "Ad Te Ipsum Tutamen a un'Frigore"
    }
}